-- SUPABASE DATABASE SETUP MIGRATION
-- This script sets up the required tables, triggers, and Row Level Security (RLS) policies for the KREDO Escrow platform.
-- Run this in your Supabase project's SQL Editor (https://supabase.com/dashboard/project/_/sql).

-- -------------------------------------------------------------
-- 1. PROFILES TABLE
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    first_name TEXT,
    last_name TEXT,
    role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    email_verified BOOLEAN DEFAULT FALSE,
    kyc_status TEXT DEFAULT 'Not Started' CHECK (kyc_status IN ('Not Started', 'Pending Review', 'Verified', 'Rejected')),
    kyc_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.protect_profile_security_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF current_user IN ('postgres', 'service_role', 'supabase_admin') THEN
    RETURN NEW;
  END IF;
  IF NOT public.is_admin() THEN
    IF NEW.role IS DISTINCT FROM OLD.role
       OR NEW.kyc_status IS DISTINCT FROM OLD.kyc_status
       OR NEW.kyc_notes IS DISTINCT FROM OLD.kyc_notes THEN
      RAISE EXCEPTION 'Only administrators can update profile security fields';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_profile_security_fields ON public.profiles;
CREATE TRIGGER protect_profile_security_fields
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.protect_profile_security_fields();

-- Turn on RLS for public.profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Define Profile RLS Policies
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
CREATE POLICY "Users can view their own profile" 
ON public.profiles FOR SELECT 
USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

DROP POLICY IF EXISTS "System/Admins can read all profiles" ON public.profiles;
CREATE POLICY "System/Admins can read all profiles" 
ON public.profiles FOR ALL 
TO authenticated 
USING (public.is_admin())
WITH CHECK (public.is_admin());

-- Profile trigger on user signup in Auth schema
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, first_name, last_name, role, email_verified, kyc_status, created_at)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'first_name', ''),
    COALESCE(new.raw_user_meta_data->>'last_name', ''),
    'user',
    FALSE,
    'Not Started',
    NOW()
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- -------------------------------------------------------------
-- 2. KYC REQUESTS TABLE
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.kyc_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    document_type TEXT NOT NULL,
    document_number TEXT NOT NULL,
    document_front_url TEXT NOT NULL, -- Path relative to bucket 'kyc-documents'
    selfie_url TEXT NOT NULL,         -- Path relative to bucket 'kyc-documents'
    status TEXT DEFAULT 'Pending Review' CHECK (status IN ('Not Started', 'Pending Review', 'Verified', 'Rejected')),
    admin_notes TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.kyc_requests
  ADD COLUMN IF NOT EXISTS email TEXT;

ALTER TABLE public.kyc_requests
  DROP CONSTRAINT IF EXISTS kyc_requests_status_check;
ALTER TABLE public.kyc_requests
  ADD CONSTRAINT kyc_requests_status_check
  CHECK (status IN ('Not Started', 'Pending Review', 'Verified', 'Rejected'));

-- Index on user_id for swift lookups
CREATE INDEX IF NOT EXISTS idx_kyc_requests_user_id ON public.kyc_requests (user_id);

-- Turn on RLS for kyc_requests
ALTER TABLE public.kyc_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own kyc request" ON public.kyc_requests;
CREATE POLICY "Users can view their own kyc request"
ON public.kyc_requests FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can upsert their own kyc request" ON public.kyc_requests;
DROP POLICY IF EXISTS "Users can create their own pending KYC request" ON public.kyc_requests;
CREATE POLICY "Users can create their own pending KYC request"
ON public.kyc_requests FOR INSERT TO authenticated
WITH CHECK (
  auth.uid() = user_id
  AND status = 'Pending Review'
  AND COALESCE(admin_notes, '') = ''
);

DROP POLICY IF EXISTS "Users can resubmit their own pending KYC request" ON public.kyc_requests;
CREATE POLICY "Users can resubmit their own pending KYC request"
ON public.kyc_requests FOR UPDATE TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (
  auth.uid() = user_id
  AND status = 'Pending Review'
  AND COALESCE(admin_notes, '') = ''
);

DROP POLICY IF EXISTS "Admins can view and manage all KYC requests" ON public.kyc_requests;
CREATE POLICY "Admins can view and manage all KYC requests"
ON public.kyc_requests FOR ALL
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

CREATE OR REPLACE FUNCTION public.sync_kyc_profile_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.profiles
  SET
    kyc_status = NEW.status,
    kyc_notes = COALESCE(NEW.admin_notes, '')
  WHERE id = NEW.user_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_kyc_profile_status ON public.kyc_requests;
CREATE TRIGGER sync_kyc_profile_status
AFTER INSERT OR UPDATE OF status, admin_notes ON public.kyc_requests
FOR EACH ROW EXECUTE FUNCTION public.sync_kyc_profile_status();

-- -------------------------------------------------------------
-- 3. CONTACT REQUESTS TABLE
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.contact_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    topic TEXT NOT NULL,
    message TEXT NOT NULL,
    destination_email TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.contact_requests
  ADD COLUMN IF NOT EXISTS destination_email TEXT;

-- Turn on RLS for contact_requests
ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can submit contact requests" ON public.contact_requests;
CREATE POLICY "Anyone can submit contact requests"
ON public.contact_requests FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can view and manage all contact requests" ON public.contact_requests;
CREATE POLICY "Admins can view and manage all contact requests"
ON public.contact_requests FOR ALL
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());


-- -------------------------------------------------------------
-- 4. NOTIFICATIONS TABLE
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT NOT NULL, -- e.g. 'system', 'escrow', 'kyc', 'news'
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Index on user_id for notifications
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications (user_id);

-- Turn on RLS for notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own notifications" ON public.notifications;
CREATE POLICY "Users can view their own notifications"
ON public.notifications FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update read status on their own notifications" ON public.notifications;
CREATE POLICY "Users can update read status on their own notifications"
ON public.notifications FOR UPDATE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins/System can insert notifications" ON public.notifications;
CREATE POLICY "Admins/System can insert notifications"
ON public.notifications FOR INSERT
TO authenticated
WITH CHECK (public.is_admin());

CREATE OR REPLACE FUNCTION public.notify_kyc_submission()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.status = 'Pending Review'
     AND (TG_OP = 'INSERT' OR OLD.status IS DISTINCT FROM NEW.status) THEN
    INSERT INTO public.notifications (user_id, title, message, type)
    VALUES (
      NEW.user_id,
      'KYC submitted',
      'Документи надіслано на перевірку',
      'kyc'
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_kyc_submission ON public.kyc_requests;
CREATE TRIGGER notify_kyc_submission
AFTER INSERT OR UPDATE OF status ON public.kyc_requests
FOR EACH ROW EXECUTE FUNCTION public.notify_kyc_submission();


-- -------------------------------------------------------------
-- 5. STORAGE BUCKET CONFIGURATION (kyc-documents)
-- -------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('kyc-documents', 'kyc-documents', false)
ON CONFLICT (id) DO UPDATE SET public = false;

DROP POLICY IF EXISTS "Users upload their own KYC files" ON storage.objects;
CREATE POLICY "Users upload their own KYC files"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'kyc-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "Users view their own KYC files" ON storage.objects;
CREATE POLICY "Users view their own KYC files"
ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'kyc-documents'
  AND ((storage.foldername(name))[1] = auth.uid()::text OR public.is_admin())
);

DROP POLICY IF EXISTS "Users replace their own KYC files" ON storage.objects;
CREATE POLICY "Users replace their own KYC files"
ON storage.objects FOR UPDATE TO authenticated
USING (
  bucket_id = 'kyc-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'kyc-documents'
  AND (storage.foldername(name))[1] = auth.uid()::text
);
